# Generated by Django 3.1.5 on 2021-04-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=21, unique=True)),
                ('avator_image', models.CharField(max_length=100)),
                ('create_ip', models.CharField(max_length=21)),
                ('user_name', models.CharField(max_length=8)),
                ('user_pwd', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=16)),
                ('invite_number', models.IntegerField()),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('user_mobile', models.CharField(max_length=13, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('deviceid', models.CharField(max_length=64)),
                ('platform', models.CharField(max_length=15)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=240)),
                ('token_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Up_Time', models.TimeField(auto_now=True)),
                ('Up_ImageUrl', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='照片')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
